.

diff --git a/build.yml b/build.yml
--- a/build.yml
+++ b/build.yml
@@ -1,31 +1,76 @@
-name: Build and Deploy AstroJS
+name: Build and Deploy
 
 on:
   push:
     branches:
       - main
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
+
+env:
+  BUILD_PATH: "." # default value when not using subfolders
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: write
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Install dependencies
-        run: npm install
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
 
-      - name: Build AstroJS
-        run: npm run build
-
-      - name: Deploy to Server
-        uses: wei/rclone@v1
-        env:
-            RCLONE_CONFIG_SFTP_TYPE: sftp
-            RCLONE_CONFIG_SFTP_HOST: ${{ secrets.SFTP_SERVER }}
-            RCLONE_CONFIG_SFTP_PORT: ${{ secrets.SFTP_PORT }}
-            RCLONE_CONFIG_SFTP_USER: ${{ secrets.SFTP_USER }}
-            #RCLONE_CONFIG_SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
+      - name: Setup Node
+        uses: actions/setup-node@v3
         with:
-            args: sync --sftp-pass $(rclone obscure ${{ secrets.SFTP_PASSWORD }}) dist sftp:/ --progress
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        working-directory: ${{ env.BUILD_PATH }}
+
+      - name: Build Astro
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} astro build
+        working-directory: ${{ env.BUILD_PATH }}
+
+      - name: Commit Changes
+        uses: stefanzweifel/git-auto-commit-action@v4
+        if: success()
+        with:
+          commit_message: Automatic Build
+
+      - name: Webhook
+        uses: distributhor/workflow-webhook@v1
+        if: success() && env.webhook_url != null
+        env:
+          webhook_url: ${{ secrets.webhook_url }}
+          webhook_secret: false
+          verify_ssl: false
